version: 2
jobs:
  build:
    working_directory: ~/data-list
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: yarn 
      - run:
          name: Test React 
          command: yarn test